{% set name = "starlette-testclient" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlette_testclient-{{ version }}.tar.gz
  sha256: 9e2c9ed5bdb8992647f657dc30bbeeb989b9273cef4b3fbbbf5ffde2d29a591a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - starlette
    - requests

test:
  imports:
    - starlette_testclient
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A backport of Starlette TestClient using requests!
  home: https://github.com/Kludex/starlette-testclient
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
